# docker-compose.yaml
version: "3"

services:
  db:
    container_name: mariadb2
    restart: always
    build:
      context: .
      args:
        buildno: 1.0
    ports:
      - ${DB_PORT}:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
