version: "3"
services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    # 환경 변수 설정
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    # 볼륨 설정
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
